xcodeproj '../prj/TookTODO.xcodeproj'

platform :'ios', '7.0'

inhibit_all_warnings!

target 'TookTODO' do

pod 'ReactiveCocoa'
pod 'PromiseKit'
pod 'AFNetworking'
pod 'AFNetworking-RACExtensions'
pod 'PromiseKit-AFNetworking'
pod 'Reachability-RACExtensions'
pod 'SVProgressHUD'
pod 'SAInfiniteScrollView'
pod 'UICKeyChainStore'
pod 'ECSlidingViewController'

end