xcodeproj '../prj/TookTODO.xcodeproj'

platform :'ios', '7.0'

inhibit_all_warnings!

target 'TookTODO' do

pod 'ReactiveCocoa'
#pod 'PromiseKit'
pod 'AFNetworking'
pod 'AFNetworking-RACExtensions'
#pod 'PromiseKit-AFNetworking'
pod 'Reachability-RACExtensions'
pod 'SVProgressHUD'
pod 'SAInfiniteScrollView'
pod 'UICKeyChainStore'
pod 'ECSlidingViewController'
pod 'RSKImageCropper'
pod 'AKNumericFormatter'
pod 'SDWebImage'
pod 'Fabric'
pod 'Crashlytics'
pod 'JSONModel'
pod 'JSONModel-RACExtensions'
pod 'Mantle'
pod 'AppDevKit'
pod 'SystemServices'
pod 'MagicalRecord'
pod 'FormatterKit'

end